### ISSUE TITLE
Where can I get getdouble and printdoubleF function?

### ISSUE THREAD

**Issue by 245950258** [syntacore/scr1#15]
I find the sc_print.c missing getdouble and printdoubleF function. Can you give me a complete sc_print.c file?
Thanks!

**Comment by eb-sc** [comment]
We don’t have these, sc_print contains a very minimalistic implementation of the print function for SCR1. 

To output floating-point numbers you could use the printf function from libc and implement the I/O functions like write(), read(), open(), close(), lseek(), etc. You can find more information in Newlib documentation (section 12 "System Calls"): https://sourceware.org/newlib/.

Best regards,
Kate
