### ISSUE TITLE
PULPissimo integration

### ISSUE THREAD

**Issue by MarekPikula** [syntacore/scr1#16]
I'm evaluating different RISC-V cores and I started with ones available for PULPissimo (ie. RI5CY and Ibex). Afterwards I've found out your project and thought that to make a fair performance comparison I could just use scr1 in PULPissimo.

I've written a wrapper to use with PULPissimo. Would you like me to push my changes to this repo and make scr1 an option in official PULPissimo repo?

**Comment by eb-sc** [comment]
Potentially, we don’t mind, - please, submit your pull request for review. We may need to keep PULPissimo-related changes in a dedicated branch, - hope that’s fine?

Best regards,
Kate

**Comment by MarekPikula** [comment]
Yeah, it would be even better. This way I could include a `src_files.yml` file, so that PULPissimo builder can easily recognize it. For now I'll send just code though.

**Comment by MarekPikula** [comment]
I'll let you know here, when there will be some development in upstream PULPissimo.

**Comment by eb-sc** [comment]
Ok, thank you.
If you still plan to include the file for PULPissimo builder or any other, you could create another pull request. The branch name is "pulpissimo_integration".

**Comment by MarekPikula** [comment]
Sure, thank you for merging.
