### ISSUE TITLE
Failing Tests With Verilator 4.034

### ISSUE THREAD

**Issue by yrrapt** [syntacore/scr1#20]
If I use Verilator 4.034 (built from source) to run the `hello` test with AHB IMC the test fails:

```
scr1_top_tb_ahb
---Test:                       hello.hex

%Error: hello.hex
:0: $readmem file not found
```

I can see that the `hello.hex` is present in the build folder.

If I instead use the Verilator 4.010 that is packaged with Debian the test passes.

**Comment by eb-sc** [comment]
Please, see an update (commit c636ac1ae0cfee0de5f023fbe07c09149c2a19ad), which in particular solves the problem with the Verilator version.

Best regards,
Kate

**Comment by yrrapt** [comment]
The fix works.  

Thanks for the help.
