### ISSUE TITLE
Verilator now supports implication in assertions, you should be able to remove ifdefs

### ISSUE THREAD

**Issue by PeterMonsson** [syntacore/scr1#21]
Hi,

I have addd support for the implication operators in Verilator. You should now be able to remove many ifdefs from the RTL code if you have Verilator 4.102.

Best Regards 
Peter

**Comment by eb-sc** [comment]
Hi Peter,

What great news! Ok, we'll remove unnecessary ifdefs in the next release.
Thank you.

Best regards,
Kate

**Comment by eb-sc** [comment]
Fixed in the latest release 3d3b544c995ebec4625150e943d985aea733809f
