### ISSUE TITLE
Error 'make tests' fails

### ISSUE THREAD

**Issue by roowatt** [syntacore/scr1#46]
I have followed the instructions for isntallation and getting started but face an issue with building tests. This is my first time looking at RISC-V based core and toolchains etc, so please be kind :)

I have the most recent master (d8ba8e50ecce3bfdd47e0422a9c024384f73df60) and sc-dt_2022.12-sp1 release of pre-built tools.

When running `make tests` I get the following error
```bash
cameron@magpie:~/projects/syntacore/scr1$ make tests
make -C /home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa ARCH=imc
make[1]: Entering directory '/home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa'
riscv64-unknown-elf-gcc -c /home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa/../../../dependencies/riscv-tests/isa/rv32ui/fence_i.S -I/home/cameron/projects/syntacore/scr1/sim/tests/common -I/home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa -DASM -Wa,-march=rv32imfc -march=rv32imfc -mabi=ilp32f -D__riscv_xlen=32 -o /home/cameron/projects/syntacore/scr1/build/tests_AHB_MAX_imc_IPIC_1_TCM_1_VIRQ_1_TRACE_0/riscv_objs/fence_i.o
/home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa/../../../dependencies/riscv-tests/isa/rv32ui/../rv64ui/fence_i.S: Assembler messages:
/home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa/../../../dependencies/riscv-tests/isa/rv32ui/../rv64ui/fence_i.S:24: Error: unrecognized opcode `fence.i'
/home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa/../../../dependencies/riscv-tests/isa/rv32ui/../rv64ui/fence_i.S:37: Error: unrecognized opcode `fence.i'
make[1]: *** [Makefile:33: /home/cameron/projects/syntacore/scr1/build/tests_AHB_MAX_imc_IPIC_1_TCM_1_VIRQ_1_TRACE_0/riscv_objs/fence_i.o] Error 1
make[1]: Leaving directory '/home/cameron/projects/syntacore/scr1/sim/tests/riscv_isa'
make: *** [Makefile:219: riscv_isa] Error 2
```

After a little investigation it seems to be a related to binutils v2.38 or newer.

From https://www.mail-archive.com/bug-binutils@gnu.org/msg40386.html

> From version 2.38, binutils default to ISA spec version 20191213. This
> means that the csr read/write (csrr*/csrw*) instructions and fence.i
> instruction has separated from the `I` extension, become two standalone
> extensions: Zicsr and Zifencei.
> 
> The fix is to specify those extensions explicitly in -march. However as
> older binutils version do not support this, we first need to detect
> that.
> 

Of course it could be more complicated.

**Comment by achuykov-sc** [comment]
Hi @roowatt,

Apologies for inconvenience with the latest toolchain. The issue happens because of build system. Please use this version of the toolchain to build application for SCR1:
- https://t.ly/2UXn for Linux
- https://t.ly/8u6b for Windows

Best regards,
Alexander
