### ISSUE TITLE
Error when running Dhrystone

### ISSUE THREAD

**Issue by lokki11199** [syntacore/scr1#59]
Hello,
I get the following error when running Dhrystone:
![image](https://github.com/syntacore/scr1/assets/131533616/16e7b0ad-b7f8-4411-83f9-29815feac405)
I am using your Pre-built RISC-V GCC toolchain from http://syntacore.com/page/products/sw-tools.
At the same time, all other tests run without errors

Thank you!

**Comment by achuykov-sc** [comment]
Hi @lokki11199,

Let me apologize for inconvenience. It is known issue. To fix it, please open `sim/tests/common/common.mk` and add `--specs=nano.specs` to the line 15:
```
LDFLAGS   ?= -nostartfiles -nostdlib -lc -lgcc -march=rv32$(ARCH)_zicsr_zifencei -mabi=$(ABI) --specs=nano.specs
```

We will fix it permanently in the next SCR1 release. 

Best regards,
Alexander

**Comment by lokki11199** [comment]
Thanks for the reply! It works.
