### ISSUE TITLE
any plan to integrate the axi interface to the sram?

### ISSUE THREAD

**Issue by yuz835** [syntacore/scr1#6]
you are using AHB-lite to connect the sram,
any plan to integrate the axi bus instead of AHB?

**Comment by ar-sc** [comment]
yes, will add in one of the coming updates. probably, not instead of ahb, though, but rather, as a configurable option.

**Comment by yuz835** [comment]
thank you

**Comment by ar-sc** [comment]
added in cbe5a3488704caff69e0bfc79804a7536356cd93
