### ISSUE TITLE
Unaligned data access exceptions are not reported in simulation

### ISSUE THREAD

**Issue by gambaman** [syntacore/scr1#62]
Hello. I used the option TRACE=1 to enable tracelog generation. The simulated program carried out an unaligned data access. However, no exception was reported in the log file.

The unaligned data access was forced using this code:

`
#define untyped_address(x) ((void *)(&x))
#define skewed_address(x) (untyped_address(x)+sizeof(x)-1)
#define alien_address(x) ((typeof(x)*)skewed_address(x))
#define alien_format(x) (*alien_address(x))

int main()
{
  int fails=0;
	int32_t mytable[8],myvar,A;
  int32_t* puntero;
	uint32_t B;
	uint8_t i;
	myvar=0x12345678;

  //enable_AEBO;

  puntero=alien_address(mytable[4]);
  sc_printf("%x\n", puntero);
	*puntero=myvar;
  sc_printf("%x\n", *puntero);

//unaligned data access above
`

**Comment by achuykov-sc** [comment]
Hi @gambaman,

I do not see any issues here because compiler is too smart and optimize `*puntero=myvar;` store away. According the disassembly:
```
...
    1514:	07800793          	li	a5,120 <-- this is 0x78
    1518:	05600293          	li	t0,86 <-- this is 0x56
    151c:	03400313          	li	t1,52 <-- this is 0x34
    1520:	43c9                	li	t2,18 <-- this is 0x12
    1522:	67858593          	addi	a1,a1,1656 # 12345678 <__C_STACK_TOP__+0x12335678>
    1526:	00f109a3          	sb	a5,19(sp) <-- push 0x12345678 in stack
    152a:	00510a23          	sb	t0,20(sp)
    152e:	00610aa3          	sb	t1,21(sp)
    1532:	00710b23          	sb	t2,22(sp)
    1536:	3f79                	jal	14d4 <sc_printf> <-- print it 
...
```

Even if you add a `volatile` qualifier for pointer `*puntero`, this does not help because **compiler** recognizes unaligned address access and do bytes store and loads. 

So, if you would catch unaligned access, you could use this snippet:  
```C
volatile int32_t * ptr;//<-- this should be volatile for test! 
uint8_t array[sizeof(int32_t)*2];
volatile int32_t offset = 1; //<-- this should be volatile for test! 

int main()
{
    ptr = (int32_t *)(array + offset);

    sc_printf("%x\n", ptr);
    *ptr=0x12345678;
    sc_printf("%x\n", *ptr);

    return 0;
}
```

And here is the output
```
...
---Test:                      unalign.hex
2381
Test failed
...
```

And trace log with MCAUSE = 6 aka Store/AMO address misaligned
```
...
            1876   N   0000151e   12342023   00001522   x07_t2     12345678
            1878   E   00001522   0000430c   000001c0   mstatus    00001800
            1878   E   00001522   0000430c   000001c0   mepc       00001522
            1878   E   00001522   0000430c   000001c0   mcause     00000006
            1878   E   00001522   0000430c   000001c0   mtval      00002381
...
```

BR,
Alexander

**Comment by gambaman** [comment]
Thank you very much for your answer, Alexander.
