### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lokki11199** [syntacore/scr1#64]
Hello,
When I try to run the makefile with the options "run_verilator_wf" or "TRACE=1", I get a segmentation fault. But from root user these options work, but only separately. For example, the output to the console when running with the options "TARGETS="hello" run_verilator_wf".
![image](https://github.com/syntacore/scr1/assets/131533616/a6eaa5fc-ec0b-492d-a2b2-4d0ac0448b36)

Thank You!

**Comment by achuykov-sc** [comment]
Hi @lokki11199,

Could you please clarify Verilator version and SCR1 version? 
Please make sure that you are using Verilator release (marked by tag) not from master branch because it may be unstable. 

Best regards,
Alexander

**Comment by lokki11199** [comment]
Thank you! Indeed, the problem was in the Verilator version.
