### ISSUE TITLE
error when running : make run_ncsim BUS=AMBA

### ISSUE THREAD

**Issue by angrej2504** [syntacore/scr1#7]
Hi I am seeing following issue when running command : make run_ncsim BUS=AMBA
into directory <some path>/scr1 -
![image](https://user-images.githubusercontent.com/34534087/34648604-1f9fbdfc-f3c2-11e7-9df2-14707eb5ea7c.png)

**Comment by as-sc** [comment]
Hello. First, there is no AMBA option, you should select AHB or AXI. The issue you're having seems to be connected with toolchain you are using. Most likely it was not properly configured. You can use our pre-built toolchain as described [here](https://github.com/syntacore/scr1#using-pre-built-binary-tools).

**Comment by angrej2504** [comment]
Oh ! Apologies.
Actually i was trying with AHB and AXI options.
And thanks for the response.

Regards,
Angrej

**Comment by ar-sc** [comment]
Closing as tools-related.
